version: '2'

services:
  whatsgoingon:
    build: .
    command: mix phoenix.server
    ports:
      - $EXPOSE_IP:4000:4000
    volumes:
      - .:/opt/:rw
    networks:
      - service-grp-net

networks:
  service-grp-net:
    external: true
